# Meson options for PortProtonQt

option('python_purelibdir', type: 'string', value: '', description: 'Python pure library installation directory (overrides purelib)')
option('udev_rulesdir', type: 'string', value: '', description: 'Udev rules installation directory (overrides default)')
option('nightly', type: 'boolean', value: false, description: 'Include git commit in application version')
option('gui', type: 'boolean', value: true, description: 'Build and install the PySide6 GUI')
