name: Code check

on:
  pull_request:
    branches: [main, scripts]
    paths-ignore:
      - "data/**"
      - "*.md"
      - "dev-scripts/**"
      - "portprotonqt/locales/**"
  push:
    branches: [main, scripts]
    paths-ignore:
      - "data/**"
      - "*.md"
      - "dev-scripts/**"
      - "portprotonqt/locales/**"
  workflow_dispatch:

jobs:
  pre-commit:
    name: Check code
    runs-on: ubuntu-latest
    container:
      image: archlinux:base-devel@sha256:84cd9ef000b3cff245ec028e87965b84724f4bf1cc63fc2741ba927b88515ed6
    steps:
      - name: Install system dependencies
        run: |
          pacman -Syuu --noconfirm --disable-download-timeout
          pacman -S --noconfirm --needed git nodejs npm mesa libarchive sdl3 pyside6 qt6-svg qt6-imageformats uv
          pacman -Scc --noconfirm

      - uses: https://git.linux-gaming.ru/actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7

      - name: Sync dependencies into venv
        run: uv sync --all-extras --dev

      - name: Activate .venv & run pre-commit
        shell: bash
        run: |
          source .venv/bin/activate
          pre-commit run --show-diff-on-failure --color=always --all-files
