name: renovate

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0'

jobs:
  renovate:
    runs-on: ubuntu-latest
    container: ghcr.io/renovatebot/renovate:latest@sha256:47421f2f3f82048e969b5195dd808d5ac2c5f69d43d192191c4a3dca390afe06
    steps:
      - uses: https://git.linux-gaming.ru/actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7

      - name: Set up Node.js
        uses: https://git.linux-gaming.ru/actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7
        with:
          node-version: 20

      - name: Install uv manually
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          . $HOME/.local/bin/env
          uv --version

      - name: Download external renovate config
        run: |
          mkdir -p /tmp/renovate-config
          curl -fsSL "https://git.linux-gaming.ru/Linux-Gaming/renovate-config/raw/branch/main/config.js" \
            -o /tmp/renovate-config/config.js

      - name: Run Renovate
        run: |
          . $HOME/.local/bin/env
          uv --version
          renovate
        env:
          RENOVATE_CONFIG_FILE: "/tmp/renovate-config/config.js"
          RENOVATE_BINARY_SOURCE: "global"
          GITHUB_COM_TOKEN: ${{ secrets.GITHUB_COM_TOKEN }}
          LOG_LEVEL: "debug"
          RENOVATE_TOKEN: ${{ secrets.RENOVATE_TOKEN }}
