#!/usr/bin/env bash
########################################################################

###BASE VARIABLES###
export PW_PROTON_LG_VER="PROTON_LG_10-30"
export PW_WINE_LG_VER="WINE_LG_11-10"
export PW_LIBS_VER="_v3.0.20260218"
export PW_PLUGINS_VER="_v20"
export D7VK_VAR_VER="v1.10"
export DXVK_NEW_VER="2.7.1-509"
export DXVK_OLD_VER="2.6.2"
export DXVK_SAREK_VER="sarek-1.11.0"
export VKD3D_NEW_VER="1.1-5122"
export VKD3D_OLD_VER="2.14.1"
export VKD3D_SAREK_VER="sarek-2.6.0"
export PW_LSFG_VK_VER="2.0.0-dev25-p11"
export PW_OPTISCALER_VER="v03-0.9.0-pre8"
export PW_SPECIALK_VER="SK_26_5_15"
export PW_EPIC_WRAPPER_VER="0.4"
export PW_GALLIUM_NINE_VER="0.10"
export DOTPFX_VER="48v9"
export DEFPFX_VER="v1"
export WINEARCH="win64"
export WINEUSERNAME="steamuser"
export WINE_WIN_START="start /wait /high /unix"
export PW_MUST_WINEDLLOVERRIDES="steam_api,steam_api64,steamclient,steamclient64=n;dotnetfx35.exe,dotnetfx35setup.exe=b;winemenubuilder.exe="
export DXVK_CONFIG_FILE="${PORT_DATA_PATH}/data/dxvk.conf"
export PW_RT_MOUNT_RO=("")
export PW_RT_MOUNT_RW=("/media" "/mnt" "/run/media/${USER}" "${PORT_DATA_PATH}")

###OTHER VARIABLES###
check_variables PW_WINE_USE "PROTON_LG"
check_variables PROTON_USE_XALIA "0"
check_variables PW_USE_RUNTIME "1"
check_variables PW_USE_D7VK "0"
check_variables PW_USE_SPECIALK "0"
check_variables PW_USE_ESYNC "0"
check_variables PW_USE_FSYNC "0"
check_variables PW_USE_NTSYNC "0"
check_variables PW_USE_GAMEMODE "0"
check_variables PW_USE_INHIBIT_SLEEP "1"
check_variables PW_USE_TERMINAL "0"
check_variables PW_WINDOWS_VER "11"
check_variables PW_USE_GSTREAMER "1"
check_variables PW_USE_D3D_EXTRAS "1"
check_variables PW_PREFIX_NAME "DEFAULT"
check_variables WINE_ALLOW_XIM "0"
check_variables PW_USE_SHADER_CACHE "1"
check_variables PW_FORCE_SYSTEM_DPI "0"
check_variables PW_WINE_DPI_VALUE "96"
check_variables PW_WINE_CPU_TOPOLOGY "disabled"
check_variables PW_MESA_GL_VERSION_OVERRIDE "disabled"
check_variables PW_MESA_VK_WSI_PRESENT_MODE "disabled"
check_variables PW_VKD3D_FEATURE_LEVEL "disabled"
check_variables PW_SOUND_DRIVER_USE "disabled"
check_variables PW_USE_EAC_AND_BE "1"
check_variables PW_USE_US_LAYOUT "0"
check_variables PW_LOCALE_SELECT "disabled"
check_variables PW_DINPUT_PROTOCOL "0"
check_variables PW_USE_VRCLIENT "0"
check_variables STAGING_SHARED_MEMORY "1"
check_variables PW_USE_GALLIUM_NINE "0"
check_variables PW_USE_GALLIUM_ZINK "0"
check_variables PW_USE_WINED3D_VULKAN "0"
check_variables PW_USE_SUPPLIED_DXVK_VKD3D "1"
check_variables PW_WINE_FULLSCREEN_FSR "1"
check_variables WINE_FULLSCREEN_FSR_MODE "0"

###DXVK_AND_VKD3D###
check_variables PW_VULKAN_USE "6"
check_variables PW_VULKAN_UNLOCKED "unlocked"
check_variables VKD3D_LIMIT_TESS_FACTORS "64"

###VKBASALT###
check_variables PW_VKBASALT "0"
check_variables PW_VKBASALT_EFFECTS "Curves:cas"
check_variables PW_VKBASALT_FFX_CAS "0.50"
check_variables PW_VKBASALT_TOOGLE_KEY "Home"
export VKBASALT_CONFIG_FILE="${PORT_DATA_PATH}/data/vkBasalt.conf"

###GAMESCOPE###
check_variables PW_GAMESCOPE "0"
check_variables PW_GS_SDL_VIDEODRIVER_X11 "0"
check_variables PW_GS_ENABLE_GAMESCOPE_WSI "0"
export PW_GAMESCOPE_ARGS_NEW=" -f --sharpness 10 --hdr-sdr-content-nits 0"

###MANGOHUD###
check_variables PW_MANGOHUD "0"
export DEFAULT_MANGOHUD_CONFIG="arch,cpu_mhz,cpu_temp,engine_version,gamemode,gpu_core_clock,gpu_mem_clock,gpu_name,gpu_temp,ram,resolution,vkbasalt,vram,vulkan_driver,wine,winesync,display_server"

###DGVOODOO2###
check_variables PW_DGVOODOO2 "0"
check_variables DGV2_VER "2.79.3"

########################################################################
pw_list_install_dll_in_prefix ()
{
    case $PW_PREFIX_NAME in
        DEFAULT)    export PW_MUST_HAVE_DLL="sandbox" ;;
        DOTNET)     export PW_MUST_HAVE_DLL="sandbox" ;;
        *)          export PW_MUST_HAVE_DLL="sandbox" ;;
    esac
}
########################################################################
add_in_start_portproton () { echo "" ;}
add_in_stop_portproton () { echo "" ;}
pw_other_fixes () { echo "" ;}
export -f add_in_stop_portproton add_in_stop_portproton pw_other_fixes
########################################################################
