"""Steam API module for PortProtonQt."""

from portprotonqt.steam_api.utils import (
    safe_vdf_load,
    decode_text,
    get_steam_home,
    get_steam_runtime_library_paths,
    get_steam_launch_commands,
    get_steam_compatibilitytools_dir,
    get_steam_compat_tool,
    get_steam_libs,
    get_steam_proton_versions,
    get_playtime_data,
    get_steam_installed_games,
    get_local_steam_cover,
    normalize_name,
    is_valid_candidate,
    filter_candidates,
    remove_duplicates,
    convert_steam_id,
    get_last_steam_user,
    get_steam_users,
)
from portprotonqt.steam_api.cache import (
    get_exiftool_data,
    delete_cached_app_files,
    load_app_details,
    save_app_details,
    load_protondb_status,
    save_protondb_status,
    build_index,
    build_weanticheatyet_index,
    build_ppdb_index,
    search_app,
    search_anticheat_status,
    search_ppdb_entry,
)
from portprotonqt.steam_api.api import (
    fetch_sgdb_cover_async,
    fetch_app_info_async,
    fetch_client_icon_async,
    get_protondb_tier_async,
    get_full_steam_game_info_async,
    get_cached_steam_game_info,
    get_steam_game_info_async,
    get_steam_apps_and_index_async,
    get_anticheat_data_and_index_async,
    get_ppdb_data_and_index_async,
    get_weanticheatyet_status_async,
    get_ppdb_info_async,
    clear_steam_api_caches,
)
from portprotonqt.steam_api.shortcuts import (
    enable_steam_cef,
    call_steam_api,
    add_to_steam,
    remove_from_steam,
    is_game_in_steam,
)

__all__ = [
    # Utils
    "safe_vdf_load",
    "decode_text",
    "get_steam_home",
    "get_steam_runtime_library_paths",
    "get_steam_launch_commands",
    "get_steam_compatibilitytools_dir",
    "get_steam_compat_tool",
    "get_steam_libs",
    "get_steam_proton_versions",
    "get_playtime_data",
    "get_steam_installed_games",
    "get_local_steam_cover",
    "normalize_name",
    "is_valid_candidate",
    "filter_candidates",
    "remove_duplicates",
    "convert_steam_id",
    "get_last_steam_user",
    "get_steam_users",
    # Cache
    "get_exiftool_data",
    "delete_cached_app_files",
    "load_app_details",
    "save_app_details",
    "load_protondb_status",
    "save_protondb_status",
    "build_index",
    "build_weanticheatyet_index",
    "build_ppdb_index",
    "search_app",
    "search_anticheat_status",
    "search_ppdb_entry",
    # API
    "fetch_sgdb_cover_async",
    "fetch_app_info_async",
    "fetch_client_icon_async",
    "get_protondb_tier_async",
    "get_full_steam_game_info_async",
    "get_cached_steam_game_info",
    "get_steam_game_info_async",
    "get_steam_apps_and_index_async",
    "get_anticheat_data_and_index_async",
    "get_ppdb_data_and_index_async",
    "get_weanticheatyet_status_async",
    "get_ppdb_info_async",
    "clear_steam_api_caches",
    # Shortcuts
    "enable_steam_cef",
    "call_steam_api",
    "add_to_steam",
    "remove_from_steam",
    "is_game_in_steam",
]
